<?php

namespace App\Traits;

use Illuminate\Support\Str;

/**
 * Add AutoGenerated Uuid when creating a new model.
 * Trait UuidAutoGenerated
 * @package App\Traits
 */
trait UuidAsPimaryKey
{
    protected static function bootUuidAsPimaryKey()
    {
        static::creating(function ($model) {
            if (! $model->getKey()) {
                $model->{$model->getKeyName()} = (string) Str::uuid();
            }
        });
    }

    public function getIncrementing()
    {
        return false;
    }

    public function getKeyType()
    {
        return 'string';
    }
}