<?php

namespace App\Traits;

use Ramsey\Uuid\Uuid;

/**
 * Add AutoGenerated Uuid when creating a new model.
 * Trait UuidAutoGenerated
 * @package App\Traits
 */
trait UuidAutoGenerated
{
    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            $model->id = (string) Uuid::uuid4();
        });
    }
}