<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Traits\UuidAutoGenerated;

/**
 * Represent a Heartbeat Listener, what you can create to listen specific key
 * for your crontask
 *
 * Class HeartbeatReceptor
 * @package App\Models
 */
class HeartbeatReceptor extends Model
{
    use UuidAutoGenerated;

    public $table = 'heartbeat_receptor';
    public $fillable = ['name', 'alertTo',];

    /*
    |--------------------------------------------------------------------------
    | Relationship
    |--------------------------------------------------------------------------
    */

    public function heartbeats()
    {
        return $this->hasMany('App\Models\Heartbeat', 'heartbeat_receptor_id');
    }
}