<?php

namespace App\Models;

use App\Models\Base\UuidModel;
use App\Traits\UuidAutoGenerated;

/**
 * Represent a Heartbeat Listener, what you can create to listen specific key
 * for your crontask
 *
 * Class HeartbeatReceptor
 * @package App\Models
 */
class HeartbeatReceptor extends UuidModel
{
    public $table = 'heartbeat_receptor';
    protected $fillable = ['name', 'alertTo',];

    /*
    |--------------------------------------------------------------------------
    | Relationship
    |--------------------------------------------------------------------------
    */

    public function heartbeats()
    {
        return $this->hasMany('App\Models\Heartbeat', 'heartbeat_receptor_id');
    }
}